---
- name: Create grafana src folder
  file: path=/src/grafana state=directory

- name: Create grafana opt folder
  file: path=/opt/grafana state=directory

- name: Get source
  command: wget https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.2.0.linux-x64.tar.gz -O /src/grafana.tar.gz

- name: Unzip grafana
  command: tar -xzf /src/grafana.tar.gz -C /opt/grafana --strip-components=1

- name: Remove temporary folder
  command: rm /src/grafana.tar.gz

- name: Copy configuration file
  template: src=custom.ini.j2 dest=/opt/grafana/conf/custom.ini
